# {{- $lokins := (lookup "v1" "Namespace" "" "loki") }}
# {{- if not $lokins }}
# kind: Namespace
# apiVersion: v1
# metadata:
#   annotations:
#     "helm.sh/resource-policy": keep
#   name: {{ .Values.namespace }}
#   labels:
#     name: {{ .Values.namespace }}
# {{- end }}