apiVersion: v1
kind: ConfigMap
metadata:
  name: ingestion-spec-config
  namespace: {{ .Values.namespace }}
data:
  system-events.json: |+
    {
      "type": "kafka",
      "spec": {
        "dataSchema": {
          "dataSource": "{{ .Values.datasource.system_events.name }}",
          "dimensionsSpec": {
            "dimensions": [
              {
                "type": "string",
                "name": "event_type"
              },
              {
                "type": "string",
                "name": "ctx_module"
              },
              {
                "type": "string",
                "name": "ctx_pdata_id"
              },
              {
                "type": "string",
                "name": "ctx_pdata_type"
              },
              {
                "type": "string",
                "name": "ctx_pdata_pid"
              },
              {
                "type": "string",
                "name": "error_pdata_id"
              },
              {
                "type": "string",
                "name": "error_pdata_status"
              },
              {
                "type": "string",
                "name": "error_type"
              },
              {
                "type": "string",
                "name": "error_code"
              },
              {
                "type": "string",
                "name": "error_message"
              },
              {
                "type": "string",
                "name": "error_level"
              },
              {
                "type": "string",
                "name": "ctx_dataset"
              },
              {
                "type": "string",
                "name": "ctx_dataset_type"
              },
              {
                "type": "string",
                "name": "extractor_status"
              },
              {
                "type": "string",
                "name": "validator_status"
              },
              {
                "type": "string",
                "name": "dedup_status"
              },
              {
                "type": "string",
                "name": "denorm_status"
              },
              {
                "type": "string",
                "name": "transformer_status"
              }
            ]
          },
          "timestampSpec": {
            "column": "ets",
            "format": "auto"
          },
          "metricsSpec": [
            {
              "type": "count",
              "name": "count"
            },
            {
              "type": "doubleSum",
              "name": "total_processing_time",
              "fieldName": "total_processing_time"
            },
            {
              "type": "doubleSum",
              "name": "latency_time",
              "fieldName": "latency_time"
            },
            {
              "type": "doubleSum",
              "name": "processing_time",
              "fieldName": "processing_time"
            },
            {
              "type": "doubleSum",
              "name": "extractor_job_time",
              "fieldName": "extractor_time"
            },
            {
              "type": "doubleSum",
              "name": "validator_time",
              "fieldName": "validator_time"
            },
            {
              "type": "doubleSum",
              "name": "dedup_time",
              "fieldName": "dedup_time"
            },
            {
              "type": "doubleSum",
              "name": "denorm_time",
              "fieldName": "denorm_time"
            },
            {
              "type": "doubleSum",
              "name": "transformer_time",
              "fieldName": "transformer_time"
            },
            {
              "type": "longSum",
              "name": "error_count",
              "fieldName": "error_count"
            }
          ],
          "granularitySpec": {
            "type": "uniform",
            "segmentGranularity": "{{ .Values.datasource.system_events.segment_granularity }}",
            "queryGranularity": "{{ .Values.datasource.system_events.query_granularity }}",
            "rollup": true
          }
        },
        "tuningConfig": {
          "type": "kafka",
          "maxRowsPerSegment": 5000000,
          "logParseExceptions": true
        },
        "ioConfig": {
          "type": "kafka",
          "topic": "{{ .Values.datasource.system_events.topic }}",
          "consumerProperties": {
            "bootstrap.servers": "{{ .Values.bootstrap_servers }}"
          },
          "taskCount": "{{ .Values.datasource.system_events.task_count }}",
          "replicas": "{{ .Values.datasource.system_events.replicas }}",
          "taskDuration": "{{ .Values.datasource.system_events.task_duration }}",
          "completionTimeout": "{{ .Values.datasource.system_events.task_completion }}",
          "useEarliestOffset": true,
          "inputFormat": {
            "type": "json",
            "flattenSpec": {
              "useFieldDiscovery": false,
              "fields": [
                {
                  "type": "path",
                  "name": "event_type",
                  "expr": "$.etype"
                },
                {
                  "type": "path",
                  "name": "ctx_module",
                  "expr": "$.ctx.module"
                },
                {
                  "type": "path",
                  "name": "ctx_pdata_id",
                  "expr": "$.ctx.pdata.id"
                },
                {
                  "type": "path",
                  "name": "ctx_pdata_type",
                  "expr": "$.ctx.pdata.type"
                },
                {
                  "type": "path",
                  "name": "ctx_pdata_pid",
                  "expr": "$.ctx.pdata.pid"
                },
                {
                  "type": "path",
                  "name": "ctx_dataset",
                  "expr": "$.ctx.dataset"
                },
                {
                  "type": "path",
                  "name": "ctx_dataset_type",
                  "expr": "$.ctx.dataset_type"
                },
                {
                  "type": "path",
                  "name": "ets",
                  "expr": "$.ets"
                },
                {
                  "type": "path",
                  "name": "extractor_status",
                  "expr": "$.data.pipeline_stats.extractor_status"
                },
                {
                  "type": "path",
                  "name": "extractor_time",
                  "expr": "$.data.pipeline_stats.extractor_time"
                },
                {
                  "type": "path",
                  "name": "validator_status",
                  "expr": "$.data.pipeline_stats.validator_status"
                },
                {
                  "type": "path",
                  "name": "validator_time",
                  "expr": "$.data.pipeline_stats.validator_time"
                },
                {
                  "type": "path",
                  "name": "dedup_status",
                  "expr": "$.data.pipeline_stats.dedup_status"
                },
                {
                  "type": "path",
                  "name": "dedup_time",
                  "expr": "$.data.pipeline_stats.dedup_time"
                },
                {
                  "type": "path",
                  "name": "denorm_status",
                  "expr": "$.data.pipeline_stats.denorm_status"
                },
                {
                  "type": "path",
                  "name": "denorm_time",
                  "expr": "$.data.pipeline_stats.denorm_time"
                },
                {
                  "type": "path",
                  "name": "transformer_status",
                  "expr": "$.data.pipeline_stats.transform_status"
                },
                {
                  "type": "path",
                  "name": "transformer_time",
                  "expr": "$.data.pipeline_stats.transform_time"
                },
                {
                  "type": "path",
                  "name": "total_processing_time",
                  "expr": "$.data.pipeline_stats.total_processing_time"
                },
                {
                  "type": "path",
                  "name": "latency_time",
                  "expr": "$.data.pipeline_stats.latency_time"
                },
                {
                  "type": "path",
                  "name": "processing_time",
                  "expr": "$.data.pipeline_stats.processing_time"
                },
                {
                  "type": "path",
                  "name": "error_pdata_id",
                  "expr": "$.data.error.pdata_id"
                },
                {
                  "type": "path",
                  "name": "error_pdata_status",
                  "expr": "$.data.error.pdata_status"
                },
                {
                  "type": "path",
                  "name": "error_type",
                  "expr": "$.data.error.error_type"
                },
                {
                  "type": "path",
                  "name": "error_code",
                  "expr": "$.data.error.error_code"
                },
                {
                  "type": "path",
                  "name": "error_message",
                  "expr": "$.data.error.error_message"
                },
                {
                  "type": "path",
                  "name": "error_level",
                  "expr": "$.data.error.error_level"
                },
                {
                  "type": "path",
                  "name": "error_count",
                  "expr": "$.data.error.error_count"
                }
              ]
            }
          },
          "appendToExisting": false
        }
      }
    }
